"""empty message

Revision ID: 57300ab8333d
Revises: 732008d5b868
Create Date: 2019-06-27 19:14:05.980276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57300ab8333d'
down_revision = '732008d5b868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('catename', sa.String(length=200), nullable=True))
    op.add_column('catalog', sa.Column('keypassword', sa.String(length=20), nullable=True))
    op.add_column('catalog', sa.Column('said', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'said')
    op.drop_column('catalog', 'keypassword')
    op.drop_column('catalog', 'catename')
    # ### end Alembic commands ###
